accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'), # home view/ landing page
    path('register/', views.register_user, name='register'), #registration form
    path('login/', views.login_user, name='login'), #login page
    path('logout/', views.logout_user, name='logout'), #logout page
]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    # Product URLs
    path('product/create/', views.product_create, name='product_create'),
    path('product/list/', views.product_list, name='product_list'),
    path('product/detail/<int:pk>/', views.product_detail, name='product_detail'),
    path('product/update/<int:pk>/', views.product_update, name='product_update'),
    path('product/delete/<int:pk>/', views.product_delete, name='product_delete'),

    # Category URLs
    path('category/create/', views.category_create, name='category_create'),
    path('category/list/', views.category_list, name='category_list'),
    path('category/detail/<int:pk>/', views.category_detail, name='category_detail'),
    path('category/update/<int:pk>/', views.category_update, name='category_update'),
    path('category/delete/<int:pk>/', views.category_delete, name='category_delete'),

    # Store URLs
    path('store/create/', views.store_create, name='store_create'),
    path('store/list/', views.store_list, name='store_list'),
    path('store/detail/<int:pk>/', views.store_detail, name='store_detail'),
    path('store/update/<int:pk>/', views.store_update, name='store_update'),
    path('store/delete/<int:pk>/', views.store_delete, name='store_delete'),


    # Users URLs
    path('users/', views.user_list, name='user_list'), # view users
    path('create/', views.user_create, name='user_create'),
    path('detail/<int:pk>/', views.user_detail, name='user_detail'),
    path('update/<int:pk>/', views.user_update, name='user_update'),
    path('delete/<int:pk>/', views.user_delete, name='user_delete'),

    # Stocks URLs
    path('store-stock/', views.store_stock, name='store_stock'), # display the stores
    path('stock/create/<int:store_id>/', views.stock_create, name='stock_create'), # create stock
    path('stock/list/<int:id>/', views.stock_list, name='stock_list'), # view products in the selected store
    path('stock/detail/<int:store_id>/<int:product_id>/', views.stock_detail, name='stock_detail'), # view the store product details
    path('stock-store-product/update/<int:store_id>/<int:product_id>/', views.stock_update, name='stock_update'), # update the selected product in the store
    path('stock-store-product/delete/<int:store_id>/<int:product_id>/', views.stock_delete, name='stock_delete'), # delete product

    # Customers
    path('customers/', views.customers_list, name="customers_list"), # retrieve customers list
    path('customer/create/', views.customers_create, name='customers_create'), # create customer
    path('customer/<int:id>/detail/', views.customers_detail, name='customers_detail'), # read customers detail
    path('customer/<int:id>/update/', views.customers_update, name='customers_update'), # update customer
    path('customer/<int:id>/delete/', views.customers_delete, name='customers_delete'), # delete customer

    # Debtors
    path('debtors/', views.debtors_list, name="debtors_list"), # retrieve the debtors
]

pos_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')), # accounts app
    path('admin-dashboard/', include('admin_dashboard.urls')), # accounts app
    path('inventory/', include('inventory.urls')), # inventory app
    path('stock-transfer/', include('stock_transfer.urls')), # stock_transfer app
    path('sales/', include('sales.urls')), # sales app
]

sales/urls.py
from django.urls import path
from . import views


app_name = 'sales'

urlpatterns = [
    path('', views.sales_view, name="sales"),
    path('submit_sale/', views.submit_sale, name='submit_sale'),

    # Admin urls
    path('sales-list/', views.sales_list, name='sales_list'), # view sales list
    path('sale-delete/<int:pk>/', views.sales_delete, name='sales_delete'), # delete sale
    path('delete-selected-sales/', views.delete_selected_sales, name='delete_selected_sales'), # delete multiple sales

    # Expenses
    path('expenses/', views.expense, name='expenses'), # enter expenses

    # Pay Debt
    path('debtors/pay/', views.pay_debt, name='pay_debtor'),

]

inventory/models.py
from django.db import models


class Store(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    pieces_per_carton = models.PositiveIntegerField()

    def __str__(self):
        return self.name


class Stock(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='stock')
    quantity = models.PositiveIntegerField()
    quantity_unit = models.CharField(max_length=10, choices=(('pieces', 'Pieces'), ('cartons', 'Cartons')))

    def __str__(self):
        total_cartons, remaining_pieces = self.get_total_cartons_and_pieces()
        quantity_display = f"{total_cartons} cartons" if total_cartons > 0 else ""
        if remaining_pieces > 0:
            quantity_display += f" {remaining_pieces} pieces"
        return f"{self.store.name} - {self.product.name}: {self.quantity} {self.quantity_unit} ({quantity_display})"

    def get_total_cartons_and_pieces(self):
        if self.quantity_unit == 'cartons':
            total_pieces = self.quantity * self.product.pieces_per_carton
        else:
            total_pieces = self.quantity
        total_cartons = total_pieces // self.product.pieces_per_carton
        remaining_pieces = total_pieces % self.product.pieces_per_carton
        return total_cartons, remaining_pieces


class Customer(models.Model):
    name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=20)
    location = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class PaymentMethod(models.Model):
    name = models.CharField(max_length=50)
    # code = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.name

inventory/forms.py
from django import forms
from .models import Product, Category, Store, Customer


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'


class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = '__all__'

# Customer form
class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

inventory/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Category, Store, Stock, Customer
from sales.models import Debtor
from .forms import ProductForm, CategoryForm, StoreForm, CustomerForm
# To display message
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required # only super admin can create the user


from accounts.models import User
from accounts.forms import UserRegistrationForm, UserUpdateForm

# Product
# Create
@staff_member_required(login_url='accounts:login')
def product_create(request):
    categories = Category.objects.all() # import the categories
    stores = Store.objects.all() # import the stores
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            # Success message
            messages.success(request, "A new product added...")
            return redirect('inventory:product_list')
    else:
        form = ProductForm()
    context = {
        'form': form,
        'categories': categories,
        'stores': stores
    }
    return render(request, 'admin/products/product_create.html', context)


# Read
@staff_member_required(login_url='accounts:login')
def product_list(request):
    products = Product.objects.all()
    return render(request, 'admin/products/product_list.html', {'products': products})


@staff_member_required(login_url='accounts:login')
def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'admin/products/product_detail.html', {'product': product})


# Update
@staff_member_required(login_url='accounts:login')
def product_update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    categories = Category.objects.all()  # Retrieve all categories
    stores = Store.objects.all()  # Retrieve all stores

    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            # Success message
            messages.success(request, "Product updated...")
            return redirect('inventory:product_list')
    else:
        form = ProductForm(instance=product)

    context = {
        'form': form,
        'product': product,
        'categories': categories,
        'stores': stores,
    }
    return render(request, 'admin/products/product_update.html', context)

# Delete
@staff_member_required(login_url='accounts:login')
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        # Success message
        messages.success(request, "Product deleted...")
        return redirect('inventory:product_list')
    return render(request, 'admin/products/product_delete.html', {'product': product})

# Store
@staff_member_required(login_url='accounts:login')
def store_create(request):
    if request.method == 'POST':
        form = StoreForm(request.POST)
        if form.is_valid():
            form.save()
            # Success message
            messages.success(request, "A new store added...")
            return redirect('inventory:store_list')
    else:
        form = StoreForm()
    return render(request, 'admin/stores/store_create.html', {'form': form})

@staff_member_required(login_url='accounts:login')
def store_list(request):
    stores = Store.objects.all()
    return render(request, 'admin/stores/store_list.html', {'stores': stores})

@staff_member_required(login_url='accounts:login')
def store_detail(request, pk):
    store = get_object_or_404(Store, pk=pk)
    return render(request, 'admin/stores/store_detail.html', {'store': store})

@staff_member_required(login_url='accounts:login')
def store_update(request, pk):
    store = get_object_or_404(Store, pk=pk)
    if request.method == 'POST':
        form = StoreForm(request.POST, instance=store)
        if form.is_valid():
            form.save()
            # Success message
            messages.success(request, "Store updated...")
            return redirect('inventory:store_list')
    else:
        form = StoreForm(instance=store)
    return render(request, 'admin/stores/store_update.html', {'form': form})

@staff_member_required(login_url='accounts:login')
def store_delete(request, pk):
    store = get_object_or_404(Store, pk=pk)
    if request.method == 'POST':
        store.delete()
        # Success message
        messages.success(request, "Store deleted...")
        return redirect('inventory:store_list')
    return render(request, 'admin/stores/store_delete.html', {'store': store})

# Categories
@staff_member_required(login_url='accounts:login')
def category_create(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            # Success message
            messages.success(request, "Category created...")
            return redirect('inventory:category_list')
    else:
        form = CategoryForm()
    
    return render(request, 'admin/categories/category_create.html', {'form': form})

@staff_member_required(login_url='accounts:login')
def category_list(request):
    categories = Category.objects.all()

    return render(request, 'admin/categories/category_list.html', {'categories': categories})

@staff_member_required(login_url='accounts:login')
def category_detail(request, pk):
    category = get_object_or_404(Category, pk=pk)
    return render(request, 'admin/categories/category_detail.html', {'category': category})

@staff_member_required(login_url='accounts:login')
def category_update(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            # Success message
            messages.success(request, "Category updated...")
            return redirect('inventory:category_list')
    else:
        form = CategoryForm(instance=category)
    
    return render(request, 'admin/categories/category_update.html', {'form': form})

@staff_member_required(login_url='accounts:login')
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        # Success message
        messages.success(request, "Category deleted...")
        return redirect('inventory:category_list')
    
    return render(request, 'admin/categories/category_delete.html', {'category': category})

# Staff
@staff_member_required(login_url='accounts:login')
def user_list(request):
    users = User.objects.all()
    return render(request, 'admin/users/user_list.html', {'users': users})


@staff_member_required(login_url='accounts:login')
def user_create(request):
    stores = Store.objects.all()
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "User created successfully.")
            return redirect('inventory:user_list')
    else:
        
        form = UserRegistrationForm()
    context = {
        'stores': stores,
        'form': form
    }
    
    return render(request, 'admin/users/user_create.html', context)


@staff_member_required(login_url='accounts:login')
def user_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    return render(request, 'admin/users/user_detail.html', {'user': user})


@staff_member_required(login_url='accounts:login')
def user_update(request, pk):
    stores = Store.objects.all()
    user = get_object_or_404(User, pk=pk)
    
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "User updated successfully.")
            return redirect('inventory:user_list')
    else:
        form = UserUpdateForm(instance=user)
    
    context = {
        'stores': stores,
        'form': form,
        'user': user,
    }
    
    return render(request, 'admin/users/user_update.html', context)

@staff_member_required(login_url='accounts:login')
def user_delete(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        user.delete()
        messages.success(request, "User deleted successfully.")
        return redirect('inventory:user_list')
    
    return render(request, 'admin/users/user_delete.html', {'user': user})


# Stock
# Stock stores
@staff_member_required(login_url='accounts:login')
def store_stock(request):
    stores = Store.objects.all()
    context = {
        'stores': stores,
    }
    return render(request, 'admin/stock/store_stock.html', context)


# Create stock for a product in a store
@staff_member_required(login_url='accounts:login')
def stock_create(request, store_id):
    store = get_object_or_404(Store, id=store_id)

    if request.method == 'POST':
        # Handle form submission and create the stock data
        product_id = request.POST.get('product')
        quantity = request.POST.get('quantity')
        
        # Retrieve the product
        product = get_object_or_404(Product, id=product_id)
        
        # Create the stock object
        stock = Stock.objects.create(store=store, product=product, quantity=quantity)
        messages.success(request, "Stock created successfully.")
        return redirect('inventory:stock_list', id=store.id)

    # Retrieve all products to populate the product selection field
    products = Product.objects.all()

    context = {
        'store': store,
        'products': products,
    }
    return render(request, 'admin/stock/stock_create.html', context)


# Products in store
@staff_member_required(login_url='accounts:login')
def stock_list(request, id):

templates/inventory/customers.html
{% extends 'common/base.html' %}
{% block title %}Customers | Clarion POS {% endblock %}
{% block content %}
  <!-- To display the messages -->
  <!-- The messages -->
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}


  <!-- To let the message disappear after a few seconds -->
  <script>
      setTimeout(function() {
          $('.alert').fadeOut('slow');
      }, 3000);
  </script>

  
  <div class="container">
    <div class="card">
        <!-- Header -->
        <div class="card-header">
          <div class="d-flex justify-content-between align-items-center">
            <h3>Customers List</h3>
            <div>
              <a class="btn btn-secondary rounded mr-2" href="{% url 'accounts:home' %}">
                <i class="fa fa-chevron-left mr-1"></i>Back to Dashboard
              </a>
              <a class="btn btn-success rounded" href="{% url 'inventory:customers_create' %}" style="margin-left: 10px;">
                <i class="fa fa-plus mr-2" style="font-size: 20px;"></i>Add Customer
              </a>
            </div>
          </div>
        </div>
        <!-- End of header -->
        <!-- Card body -->
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="thead-light">
                        <tr>
                            <th>Name</th>
                            <th>Phone Number</th>
                            <th>Location</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for customer in customers %}
                        <tr>
                            <td>{{ customer.name }}</td>
                            <td>{{ customer.phone_number }}</td>
                            <td>{{ customer.location }}</td>
                            <td>
                              <div class="btn-group">
                                  <a class="btn btn-primary mr-2 rounded" href="{% url 'inventory:customers_detail' customer.id %}">Detail</a>
                                  <a class="btn btn-warning mr-2 rounded" href="{%url 'inventory:customers_update' customer.id  %}">Update</a>
                                  <a class="btn btn-danger mr-2 rounded" href="{% url 'inventory:customers_delete' customer.id %}">Delete</a>
                              </div>
                          </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <!-- End of card body -->
    </div>
  </div>

{% endblock %}

templates/inventory/customers_create.html
{% extends 'common/base.html' %}
{% block title %}Create Customer{% endblock %}
{% block content %}
  <!-- To display the messages -->
  <!-- The messages -->
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}


  <!-- To let the message disappear after a few seconds -->
  <script>
      setTimeout(function() {
          $('.alert').fadeOut('slow');
      }, 3000);
  </script>

<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>Create Customer</h3>
        </div>
        <div class="card-body">
            <form method="POST" action="">
                <!-- Form errors -->
                {% if form.errors %}
                <div class="alert alert-danger"> 
                    {% for error in form.errors %}
                        <strong>Error in creating the customer</strong><br>Please try again
                    {% endfor %}  
                </div>
                {% endif %} 
                <!-- End of form errors -->
                {% csrf_token %}
                <!-- Name -->
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter customer name" required>
                </div>
                <!-- Phone number -->
                <div class="form-group">
                    <label for="phone_number">Phone Number</label>
                    <input type="tel" class="form-control" id="phone_number" name="phone_number" placeholder="Enter phone number" required>
                </div>
                <!-- Location -->
                <div class="form-group">
                    <label for="name">Location</label>
                    <input type="" class="form-control" id="location" name="location" placeholder="Enter customer address" required>
                </div>
                <button type="submit" class="btn btn-primary">Create</button>
                <a href="{% url 'inventory:customers_list' %}" class="btn btn-secondary">Back</a>
            </form>
        </div>
    </div>
</div>



{% endblock %}

templates/inventory/customers_delete.html
{% extends 'common/base.html' %}
{% block title %}Delete Store{% endblock %}
{% block content %}
  <div class="container">
    <h3>Delete Customer</h3>
    <p>Are you sure you want to delete the customer "{{ customer.name }}"?</p>
    <form method="POST">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger">Delete</button>
      <a href="{% url 'inventory:customers_detail' customer.id %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

templates/inventory/customers_detail.html
{% extends 'common/base.html' %}
{% block title %}View User{% endblock %}
{% block content %}
  <!-- To display the messages -->
  {% if messages %}
    <div class="alert alert-{{ messages.tags }} alert-dismissible fade show" role="alert">
      {{ messages }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endif %}

 <!-- To let the message disappear after a few seconds -->
 <script>
    setTimeout(function() {
        $('.alert').fadeOut('slow');
    }, 3000);
</script>

<div class="container">
    <div class="card">
      <div class="card-header">
        <h3>Customer Details</h3>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col">
            <div class="card">
              <div class="card-header">
                <h4>Personal Information</h4>
              </div>
              <div class="card-body">
                <p><strong>Name:</strong> {{ customer.name }}</p>
                <p><strong>Phone Number:</strong> {{ customer.phone_number }}</p>
                <p><strong>Location:</strong> {{ customer.location }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <a href="{% url 'inventory:customers_update' customer.id %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'inventory:customers_delete' customer.id %}" class="btn btn-danger">Delete</a>
        <a href="{% url 'inventory:customers_list' %}" class="btn btn-secondary">Back</a>
      </div>
    </div>
  </div>
  



{% endblock %}

templates/inventory/customers_update.html
{% extends 'common/base.html' %}
{% block title %}Update User{% endblock %}
{% block content %}
  <!-- To display the messages -->
  {% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
{% endif %}

 <!-- To let the message disappear after a few seconds -->
 <script>
    setTimeout(function() {
        $('.alert').fadeOut('slow');
    }, 3000);
</script>


<div class="container">
    <div class="card">
      <div class="card-header">
        <h2>Update Customer Details</h2>
      </div>
      <!-- Form body -->
      <div class="card-body">
        <!-- Actual form -->
        <form method="POST" action="">
          {% csrf_token %}
          <!-- Form errors -->
          {% if form.errors %}
          <div class="alert alert-danger"> 
              {% for error in form.errors %}
                  <strong>Error in updating the customer</strong><br>Please try again
              {% endfor %}  
          </div>
          {% endif %} 
          <!-- End of form errors -->
          <!-- Name -->
          <div class="form-group">
            <label for="username">Name:</label>
            <input type="text" class="form-control" id="id_name" name="name" value="{{ form.name.value }}" required>
          </div>      
          <!-- Phone number -->
          <div class="form-group">
            <label for="phone_number">Phone Number:</label>
            <input type="text" class="form-control" id="id_phone_number" name="phone_number" value="{{ form.phone_number.value }}">
          </div>
            <!-- Location        -->
          <div class="form-group">
            <label for="full_name">Location:</label>
            <input type="text" class="form-control" id="id_location" name="location" value="{{ form.location.value }}">
          </div>
          <!-- Submit button -->
          <button type="submit" class="btn btn-primary">Update</button>
          <a href="{% url 'inventory:customers_detail' form.instance.id %}" class="btn btn-secondary">Cancel</a>
        </form>
        <!-- End of actual form -->
      </div>
      <!-- End of form body -->
    </div>
  </div>
  


{% endblock %}