accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'), # home view/ landing page
    path('register/', views.register_user, name='register'), #registration form
    path('login/', views.login_user, name='login'), #login page
    path('logout/', views.logout_user, name='logout'), #logout page
]

admin_dashboard/urls.py
from django.urls import path
from . import views

app_name = 'admin_dashboard'

urlpatterns = [
    path('', views.admin_dashboard, name='dashboard'), # dashboard
    
    # Sales
    path('select-store/', views.select_sale_store, name='select_sale_store'), # select the store for the sale
    path('sales/<int:id>/', views.sales_list, name='sales_list'), # view sales in the selected store
    path('sale/detail/<int:store_id>/<int:sale_id>/', views.sale_detail, name="sale_detail"), # view sale detail
    path('sale/update/<int:store_id>/<int:sale_id>/', views.sale_update, name='sale_update'), # update sale
    path('sale/delete/<int:store_id>/<int:sale_id>/', views.sale_delete, name='sale_delete'), # delete sale

    # Expenses
    path('select-expense-store/', views.select_expense_store, name='select_expense_store'), # select the store for the expense


]

pos_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')), # accounts app
    path('admin-dashboard/', include('admin_dashboard.urls')), # accounts app
    path('inventory/', include('inventory.urls')), # inventory app
    path('stock-transfer/', include('stock_transfer.urls')), # stock_transfer app
    path('sales/', include('sales.urls')), # sales app
]

sales/urls.py
from django.urls import path
from . import views


app_name = 'sales'

urlpatterns = [
    path('', views.sales_view, name="sales"),
    path('submit_sale/', views.submit_sale, name='submit_sale'),

    # Admin urls
    path('sales-list/', views.sales_list, name='sales_list'), # view sales list
    path('sale-delete/<int:pk>/', views.sales_delete, name='sales_delete'), # delete sale
    path('delete-selected-sales/', views.delete_selected_sales, name='delete_selected_sales'), # delete multiple sales

    # Expenses
    path('expenses/', views.expense, name='expenses'), # enter expenses

    # Pay Debt
    path('debtors/pay/', views.pay_debt, name='pay_debtor'),

]

stock_transfer/urls.py
from django.urls import path
from . import views

app_name = 'stock_transfer'

urlpatterns = [
    path('stock_transfer/', views.stock_transfer_view, name='stock_transfer'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

# For creating a user upon signup
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

# User should have store
from inventory.models import Store



class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        # Username is required
        if not username:
            raise ValueError('The username field is required')
        # Email is also required
        if not email:
            raise ValueError('Please enter your email address')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(username, email, password, **extra_fields)



# The User model
class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, related_name='stores', null=True, blank=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    full_name = models.CharField(max_length=255, blank=True, null=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    # To avoid the conflict of User default name
    groups = models.ManyToManyField(
        'auth.Group',
        blank=True,
        related_name='myuser_set',
        related_query_name='user',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        blank=True,
        related_name='myuser_set',
        related_query_name='user',
    )

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return f"{self.username} - {self.email}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User, Store
# Authentication
from django.contrib.auth import authenticate

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    store = forms.ModelChoiceField(queryset=Store.objects.all())
    full_name = forms.CharField()
    phone_number = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'store', 'email', 'full_name', 'phone_number', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.full_name = self.cleaned_data['full_name']
        user.phone_number = self.cleaned_data['phone_number']
        if commit:
            user.save()
        return user

class UserUpdateForm(UserChangeForm):
    email = forms.EmailField(required=True)
    store = forms.ModelChoiceField(queryset=Store.objects.all())
    full_name = forms.CharField()
    phone_number = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'store', 'email', 'full_name', 'phone_number')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.full_name = self.cleaned_data['full_name']
        user.phone_number = self.cleaned_data['phone_number']
        if commit:
            user.save()
        return user


# Login Form
class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
       
        user = authenticate(username=username, password=password)
        if not user:
            self.add_error('', 'Invalid username or password')
            raise forms.ValidationError('Please check the credentials you provided')
        return cleaned_data

accounts/views.py
from django.shortcuts import render, redirect
from  .forms import UserRegistrationForm, LoginForm
# To display message
from django.contrib import messages
# For authentication
from django.contrib.auth.decorators import login_required # only super admin can create the user-- has to log in
from django.contrib.admin.views.decorators import staff_member_required # only super admin can create the user
from django.contrib.auth import authenticate, login, logout
# Create your views here.

# Home view
def home(request):
    return render(request, 'accounts/home.html', context={})


# Creating the user
@staff_member_required(login_url='accounts:login')
def register_user(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            # Success message
            messages.success(request, "Congratulations! You have created an account successfully! Now login below...")
            return redirect('accounts:login') # the login url pattern
        # If error in creation
        else:
            messages.error(request, 'There was an error while creating your account. Please try again.')
    else:
        form = UserRegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})

# Login
def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            # If user exist
            if user is not None:
                login(request, user)
                if user.is_superuser:
                    # Success message
                    messages.success(request, "Welcome Admin... You have logged in successfully!")
                    # Redirect super admin to the dashboard
                    return redirect('admin_dashboard:dashboard')
                else:
                    # Success message
                    messages.success(request, "Congratulations! You have logged in successfully!")
                    # Redirect new users to the home page
                    return redirect('accounts:home')
                    
                # # Redirect them
                # return redirect('accounts:home')
            # else:
            #     # Error message if credentials are wrong
            #     form.add_error(None, 'Invalid username or password')
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})

# Logout
def logout_user(request):
    logout(request)
    # Success message
    messages.success(request, "We hope we have been of use to you...")
    return render(request, 'accounts/logout.html')

templates/accounts/home.html
{% extends 'common/base.html' %}

{% block title %}Clarion Point of Sale System{% endblock %}

{% block content %}
  <!-- To display the messages -->
  <!-- The messages -->
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}


  <!-- To let the message disappear after a few seconds -->
  <script>
      setTimeout(function() {
          $('.alert').fadeOut('slow');
      }, 3000);
  </script>
  <!-- Content -->
  <!-- Top jumbotron -->
  <div class="jumbotron jumbotron-fluid bg-green">
    <div class="container text-center">
      <h1 class="display-4">Welcome to Clarion Point of Sale System</h1>
      <p class="lead">A quick and easy experience with stock management and making sales</p>
      {% if user.is_authenticated %}
        {% if user.is_superuser %}
          <a class="btn btn-outline-info btn-lg mx-2" href="{% url 'admin_dashboard:dashboard' %}" role="button">View Dashboard</a>
        {% else %}
        <a class="btn btn-outline-info btn-lg mx-2" href="{% url 'sales:sales' %}" role="button">Make Sales</a>
        <a class="btn btn-outline-warning btn-lg mx-2" href="{% url 'stock_transfer:stock_transfer' %}" role="button">Stock Transfer</a>
        {% endif %}
        
      {% else %}
        <a class="btn btn-outline-info btn-lg btn-block" href="{% url 'accounts:login' %}" role="button">Login</a>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/accounts/login-org.html
{% extends 'common/base.html' %}

{% load static %}

{% block title %}
    Login | Clarion POS
{% endblock %}

{% block content %}
<!-- The messages -->
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
{% endif %}


<!-- To let the message disappear after a few seconds -->
<script>
    setTimeout(function() {
        $('.alert').fadeOut('slow');
    }, 3000);
</script>



<section class="section section-content padding-y" style="min-height: 84vh;">
    <div class="container d-flex justify-content-center">
        <div class="card-body">
            <div class="row">
                <!-- Form image -->
                <div class="container container--mini">
                    <img class="img-fluid mx-auto d-block mb-5 img rounded" src="{% static 'images/logos/clarion_logo.svg' %}" style="height: fit-content; width: 200px;" alt="KAFU Logo">
                <form method="post" class="form-signup mx-auto d-block mb-5" style="width: 400px;">
                    {% csrf_token %}
                    <!-- To handle errors -->
                    {% if form.errors %}
                    <div class="alert alert-danger"> 
                        {% for error in form.errors %}
                            <strong>Invalid username or password</strong><br>Please try again
                        {% endfor %}  
                    </div>
                    {% endif %}
                    <h2 class="form-signup-heading">Login</h2>
                    <!-- Username -->
                    <div class="form-group">
                        <label for="id_username">Username</label>
                        <input type="text" class="form-control" name="username" maxlength="100" placeholder="Enter your username" required="" id="id_username" value="{{ form.username.value|default:'' }}">
                    </div>
                    
                    <!-- Password -->
                    <div class="form-group">
                        <label for="id_password">Password:</label>
                        <input type="password" class="form-control" name="password" placeholder="Enter password" autocomplete="new-password" required="" id="id_password">
    
                    </div>
                    <input type="hidden" name="next" value="">
                    <!-- Submit -->
                    <button type="submit" class="btn btn  btn-primary">Log In</button>
                </form>
                
            </div>
            
        </div>
        
    </div>
    <!-- Success -->
    
    
</section>
{% endblock %}

templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
<!-- The messages -->
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
{% endif %}

<!-- To let the message disappear after a few seconds -->
<script>
  setTimeout(function() {
      $('.alert').fadeOut('slow');
  }, 3000);
</script>

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Login
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
              {% if msg %}
                <span class="text-danger">{{ msg | safe }}</span>
              {% else %}
                  Enter your credentials
              {% endif %}  
          </h6>
          
          <br />

          <form role="form" method="post" action="">
              
            {% csrf_token %}
            {% if form.errors %}
            <div class="alert alert-danger"> 
                {% for error in form.errors %}
                    <strong>Invalid username or password</strong><br>Please try again
                {% endfor %}  
            </div>
            {% endif %} 

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label for="id_username" class="bmd-label-floating">Username</label>
                  <input type="text" class="form-control" name="username" maxlength="100" placeholder="" required="" id="id_username" value="{{ form.username.value|default:'' }}">
                </div>
              </div>
            </div>

            <br />

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label for="id_password" class="bmd-label-floating">Password</label>
                  <input type="password" class="form-control" name="password" placeholder="" autocomplete="new-password" required="" id="id_password">
                </div>
              </div>
            </div>
            <input type="hidden" name="next" value="">
            <br />

            <button type="submit" name="login" class="btn btn-block btn-primary pull-left">Login</button>

            &nbsp; &nbsp; 
            <span class="pull-right">
              Don't have an account? <p class="text-primary">Ask the admin to create one for you</p>
            </span>

            <div class="clearfix"></div>

          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/accounts/logout.html
{% extends 'common/base.html' %}
{% block title %}Logout{% endblock %}
{% block content %}

<!-- The messages -->
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
{% endif %}


<!-- To let the message disappear after a few seconds -->
<script>
    setTimeout(function() {
        $('.alert').fadeOut('slow');
    }, 3000);
</script>

<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">Good bye...</div>
        <div class="card-body">
          <p>You have been successfully logged out.</p>
          <a href="{% url 'accounts:login' %}" class="btn btn-primary">Login Again?</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}