accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name='home'), # home view/ landing page
    path('register/', views.register_user, name='register'), #registration form
    path('login/', views.login_user, name='login'), #login page
    path('logout/', views.logout_user, name='logout'), #logout page
]

admin_dashboard/urls.py
from django.urls import path
from . import views

app_name = 'admin_dashboard'

urlpatterns = [
    path('', views.admin_dashboard, name='dashboard'), # dashboard
    
    # Sales
    path('select-store/', views.select_sale_store, name='select_sale_store'), # select the store for the sale
    path('sales/<int:id>/', views.sales_list, name='sales_list'), # view sales in the selected store
    path('sale/detail/<int:store_id>/<int:sale_id>/', views.sale_detail, name="sale_detail"), # view sale detail
    path('sale/update/<int:store_id>/<int:sale_id>/', views.sale_update, name='sale_update'), # update sale
    path('sale/delete/<int:store_id>/<int:sale_id>/', views.sale_delete, name='sale_delete'), # delete sale

    # Expenses
    path('select-expense-store/', views.select_expense_store, name='select_expense_store'), # select the store for the expense


]

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    # Product URLs
    path('product/create/', views.product_create, name='product_create'),
    path('product/list/', views.product_list, name='product_list'),
    path('product/detail/<int:pk>/', views.product_detail, name='product_detail'),
    path('product/update/<int:pk>/', views.product_update, name='product_update'),
    path('product/delete/<int:pk>/', views.product_delete, name='product_delete'),

    # Category URLs
    path('category/create/', views.category_create, name='category_create'),
    path('category/list/', views.category_list, name='category_list'),
    path('category/detail/<int:pk>/', views.category_detail, name='category_detail'),
    path('category/update/<int:pk>/', views.category_update, name='category_update'),
    path('category/delete/<int:pk>/', views.category_delete, name='category_delete'),

    # Store URLs
    path('store/create/', views.store_create, name='store_create'),
    path('store/list/', views.store_list, name='store_list'),
    path('store/detail/<int:pk>/', views.store_detail, name='store_detail'),
    path('store/update/<int:pk>/', views.store_update, name='store_update'),
    path('store/delete/<int:pk>/', views.store_delete, name='store_delete'),


    # Users URLs
    path('users/', views.user_list, name='user_list'), # view users
    path('create/', views.user_create, name='user_create'),
    path('detail/<int:pk>/', views.user_detail, name='user_detail'),
    path('update/<int:pk>/', views.user_update, name='user_update'),
    path('delete/<int:pk>/', views.user_delete, name='user_delete'),

    # Stocks URLs
    path('store-stock/', views.store_stock, name='store_stock'), # display the stores
    path('stock/create/<int:store_id>/', views.stock_create, name='stock_create'), # create stock
    path('stock/list/<int:id>/', views.stock_list, name='stock_list'), # view products in the selected store
    path('stock/detail/<int:store_id>/<int:product_id>/', views.stock_detail, name='stock_detail'), # view the store product details
    path('stock-store-product/update/<int:store_id>/<int:product_id>/', views.stock_update, name='stock_update'), # update the selected product in the store
    path('stock-store-product/delete/<int:store_id>/<int:product_id>/', views.stock_delete, name='stock_delete'), # delete product

    # Customers
    path('customers/', views.customers_list, name="customers_list"), # retrieve customers list
    path('customer/create/', views.customers_create, name='customers_create'), # create customer
    path('customer/<int:id>/detail/', views.customers_detail, name='customers_detail'), # read customers detail
    path('customer/<int:id>/update/', views.customers_update, name='customers_update'), # update customer
    path('customer/<int:id>/delete/', views.customers_delete, name='customers_delete'), # delete customer

    # Debtors
    path('debtors/', views.debtors_list, name="debtors_list"), # retrieve the debtors
]

pos_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')), # accounts app
    path('admin-dashboard/', include('admin_dashboard.urls')), # accounts app
    path('inventory/', include('inventory.urls')), # inventory app
    path('stock-transfer/', include('stock_transfer.urls')), # stock_transfer app
    path('sales/', include('sales.urls')), # sales app
]

sales/urls.py
from django.urls import path
from . import views


app_name = 'sales'

urlpatterns = [
    path('', views.sales_view, name="sales"),
    path('submit_sale/', views.submit_sale, name='submit_sale'),

    # Admin urls
    path('sales-list/', views.sales_list, name='sales_list'), # view sales list
    path('sale-delete/<int:pk>/', views.sales_delete, name='sales_delete'), # delete sale
    path('delete-selected-sales/', views.delete_selected_sales, name='delete_selected_sales'), # delete multiple sales

    # Expenses
    path('expenses/', views.expense, name='expenses'), # enter expenses

    # Pay Debt
    path('debtors/pay/', views.pay_debt, name='pay_debtor'),

]

templates/common/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- The title of each file -->
    <title>{% block title %}{% endblock %}</title>
    <!-- For the bootstrap -->
    <!--    Link the bootstrap-->
    <script src="{% static 'bootstrap/js/jquery-3.4.0.js' %}"></script>
    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
    <!-- jquery -->
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/jquery-3' %}"></script>
    
    <!-- Chart representation -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>


    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'custom_css/styles.css' %}">
    <!-- Icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/logos/clarion_favicon.ico' %}">

    <!-- csrf-token -->
    <meta name="csrf-token" content="{{ csrf_token }}">


</head>
<body>
    <!-- The header, includes the header.html -->
    <header>
      {% include 'common/header.html' %}  
      
    </header>
    <br>
    <!-- The main body or content of the other htmls -->
    <main class="site-main main"> <!--  added site-main -->
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <br>
    <!-- The footer -->
    <footer>
        <!-- Footer content -->
        {% include 'common/footer.html' %}
    </footer>

</body>
</html>

templates/common/footer.html
{% load static %}
<footer class="footer mt-auto py-3 bg-light">
    <div class="container text-center">
      <span class="text-muted">&copy; 2023 Denzel Gitonga POS System. All rights reserved.</span>
    </div>
</footer>
  

templates/common/header.html
{% load static %}
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <!-- Admin -->
        {% if user.is_authenticated and user.is_superuser %}
          <a class="navbar-brand col-md-2" href="{% url 'admin_dashboard:dashboard' %}">
              <!-- Logo -->
              <img src="{% static 'images/logos/clarion_logo.svg' %}" alt="Logo" height="40" class="mr-2 rounded">
              Clarion Point of Sale System
          </a>
        {% else %}
        <!-- Normal user -->
          <a class="navbar-brand col-md-2" href="{% url 'accounts:home' %}">
            <!-- Logo -->
            <img src="{% static 'images/logos/clarion_logo.svg' %}" alt="Logo" height="40" class="mr-2 rounded">
            Clarion Point of Sale System
          </a>
        {% endif %}
          <button class="navbar-toggler col-md-2" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-between col-md-8" id="navbarNav">
            <!-- After login -->
            {% if user.is_authenticated %}
              {% if user.is_superuser %}
                <!-- Mid section -->
                <!-- Links -->
                <!-- Products -->
                <ul class="navbar-nav">
                <!-- Products -->
                <!-- End of Products -->

                <!-- Stores -->
                <!-- End of Stores -->

                <!-- Customers -->
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'inventory:customers_list' %}">Customers</a>
                </li>
                <!-- End of Customers -->
                
                <!-- Sales -->
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'sales:sales_list' %}">Sales</a>
                </li>
                <!-- End of Sales -->

                <!-- Stock -->
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'inventory:store_stock' %}">Stock</a>
                </li>
                <!-- End of Sales -->
                <!-- End of mid section -->
                </ul>
                <!-- Display welcome message and logout link for superuser -->
                <ul class="navbar-nav ml-auto">
                  <!-- Welcome -->
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      Welcome, {{ user.username }}
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                  </li>
                </ul>
              {% else %}
              <!-- Normal user -->
              <!-- Mid section -->
              <ul class="navbar-nav">
                <!-- Customers -->
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'inventory:customers_list' %}">Customers</a>
                </li>
                <!-- End of Customers -->
                <!-- Expenses  -->
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'sales:expenses' %}">Expenses</a>
                </li>
                <!-- End of Expenses -->
                <!-- Debtors  -->
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'inventory:debtors_list' %}">Debtors</a>
                </li>
                <!-- End of Debtors -->
              </ul>
              <!-- End of mid section -->
              <!-- Right section -->
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      Welcome, {{ user.username }}
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                  </li>
                </ul>
              <!-- End of right section -->
              {% endif %}
            {% endif %}
          </div>
      </div>
  </nav>
</header>